# -*- coding: utf-8 -*-
"""阶段 3.6:服务层按 tier 分发到正确路径,并先发 tier 事件。

打桩 run_simple / run_agent_graph,验证 react_stream:
  - 先 yield {"type":"tier", ...}
  - simple  -> run_simple
  - medium  -> run_agent_graph
  - complex -> run_agent_graph(阶段 5 前 P&E 未接入)
  - thread_id 缺省自动生成
不跑真实图 / 不连任何外部服务。
"""
from unittest.mock import patch, MagicMock

import chat.service as svc


def _stub_path(events):
    """返回一个 MagicMock,被调用时返回产出给定事件的生成器。"""
    def _gen(*a, **k):
        for ev in events:
            yield ev
    return MagicMock(side_effect=_gen)


class TestTierDispatch:
    def test_tier_event_emitted_first(self):
        with patch.object(svc, "classify_complexity",
                          return_value={"tier": "medium", "confidence": 0.9,
                                        "source": "llm"}), \
             patch.object(svc, "run_agent_graph",
                          new=_stub_path([{"type": "done"}])) as rag, \
             patch.object(svc, "run_simple", new=_stub_path([])) as rs:
            events = list(svc.react_stream("你好", [], thread_id="t1"))
        assert events[0]["type"] == "tier"
        assert events[0]["tier"] == "medium"
        assert events[0]["confidence"] == 0.9
        assert events[0]["source"] == "llm"
        rag.assert_called_once()
        rs.assert_not_called()

    def test_simple_dispatches_to_run_simple(self):
        with patch.object(svc, "classify_complexity",
                          return_value={"tier": "simple", "confidence": 0.95,
                                        "source": "rule"}), \
             patch.object(svc, "run_simple",
                          new=_stub_path([{"type": "assistant_message"},
                                          {"type": "done"}])) as rs, \
             patch.object(svc, "run_agent_graph", new=_stub_path([])) as rag:
            events = list(svc.react_stream("你好", [], thread_id="t2",
                                           username="alice", session_id="s2"))
        rs.assert_called_once()
        # 身份透传
        _, kwargs = rs.call_args
        assert kwargs["thread_id"] == "t2"
        assert kwargs["username"] == "alice"
        assert kwargs["session_id"] == "s2"
        rag.assert_not_called()
        # tier 在前,路径事件在后
        assert events[0]["type"] == "tier"
        assert events[-1]["type"] == "done"

    def test_complex_falls_back_to_react_before_stage5(self):
        with patch.object(svc, "classify_complexity",
                          return_value={"tier": "complex", "confidence": 0.85,
                                        "source": "rule"}), \
             patch.object(svc, "run_agent_graph",
                          new=_stub_path([{"type": "done"}])) as rag, \
             patch.object(svc, "run_simple", new=_stub_path([])):
            events = list(svc.react_stream("对比 ALD 和 CVD", [],
                                           thread_id="t3"))
        assert events[0]["tier"] == "complex"
        rag.assert_called_once()

    def test_thread_id_autogenerated_when_missing(self):
        captured = {}

        def _capture(*a, **k):
            captured.update(k)
            if False:
                yield  # 使其成为生成器

        with patch.object(svc, "classify_complexity",
                          return_value={"tier": "simple", "confidence": 1.0,
                                        "source": "rule"}), \
             patch.object(svc, "run_simple", side_effect=_capture):
            list(svc.react_stream("hi", []))
        assert captured.get("thread_id")  # 非空字符串
