# -*- coding: utf-8 -*-
"""服务层按 tier 分发到正确路径,并先发 tier 事件。

打桩 run_simple / run_agent_graph 与 quality_check,验证 react_stream:
  - 先 yield {"type":"tier", ...}
  - simple -> run_simple
  - react  -> run_agent_graph
  - thread_id 缺省自动生成
不跑真实图 / 不连任何外部服务。
"""
from unittest.mock import patch, MagicMock

import pytest

import chat.service as svc

# 分发编排类测试:走旧两段式入口(打桩 classify_complexity);
# ROUTER_FUSED 融合入口的接线行为在 test_fused_entry.py 覆盖。
@pytest.fixture(autouse=True)
def _legacy_router_entry(monkeypatch):
    import config as C
    monkeypatch.setattr(C, "ROUTER_FUSED", 0)

# 桩路径统一产出一条非领域答案 + done,避免 simple 领域启发式触发升级
_PASSED_GATE = {"verdict": "passed", "feedback": "", "warnings": []}
_DONE = {"type": "done", "trace": {}}


def _stub_path(extra=None):
    """返回一个 MagicMock,被调用时产出 assistant_message + 给定附加事件 + done。"""
    events = [{"type": "assistant_message", "content": "好的,我知道了。"}]
    if extra:
        events.extend(extra)
    events.append(_DONE)

    def _gen(*a, **k):
        for ev in events:
            yield ev
    return MagicMock(side_effect=_gen)


class TestTierDispatch:
    def test_tier_event_emitted_first(self):
        with patch.object(svc, "classify_complexity",
                          return_value={"tier": "react", "confidence": 0.9,
                                        "source": "llm"}), \
             patch.object(svc, "quality_check", return_value=_PASSED_GATE), \
             patch.object(svc, "run_agent_graph", new=_stub_path()) as rag, \
             patch.object(svc, "run_simple", new=_stub_path()) as rs:
            events = list(svc.react_stream("ALD 原理是什么", [], thread_id="t1"))
        assert events[0]["type"] == "tier"
        assert events[0]["tier"] == "react"
        assert events[0]["confidence"] == 0.9
        assert events[0]["source"] == "llm"
        rag.assert_called_once()
        rs.assert_not_called()
        assert events[-1]["type"] == "done"

    def test_simple_dispatches_to_run_simple(self):
        with patch.object(svc, "classify_complexity",
                          return_value={"tier": "simple", "confidence": 0.95,
                                        "source": "rule"}), \
             patch.object(svc, "quality_check", return_value=_PASSED_GATE), \
             patch.object(svc, "run_simple", new=_stub_path()) as rs, \
             patch.object(svc, "run_agent_graph", new=_stub_path()) as rag:
            events = list(svc.react_stream("你好", [], thread_id="t2",
                                           username="alice", session_id="s2"))
        rs.assert_called_once()
        # 身份透传
        _, kwargs = rs.call_args
        assert kwargs["thread_id"] == "t2"
        assert kwargs["username"] == "alice"
        assert kwargs["session_id"] == "s2"
        rag.assert_not_called()
        # tier 在前,路径事件在后
        assert events[0]["type"] == "tier"
        assert events[-1]["type"] == "done"

    def test_thread_id_autogenerated_when_missing(self):
        captured = {}

        def _capture(*a, **k):
            captured.update(k)
            yield {"type": "assistant_message", "content": "好的"}
            yield _DONE

        with patch.object(svc, "classify_complexity",
                          return_value={"tier": "simple", "confidence": 1.0,
                                        "source": "rule"}), \
             patch.object(svc, "quality_check", return_value=_PASSED_GATE), \
             patch.object(svc, "run_simple", side_effect=_capture):
            list(svc.react_stream("hi", []))
        assert captured.get("thread_id")  # 非空字符串
